export const TagTypes = {
  RESTAURANT: "Restaurant",
  USERS: "Users",
  LOGIN: "Login",
  CART: "Cart",
  PRODUCT: "Product",
  CATEGORY: "Category",
  ORDER: "Order",
  SERVICE: "Service",

  //
  PRODUCTS: "Products",
  ORDERS: "Orders",
  INVOICES: "Invoices",
  MONEY_RECEIPTS: "Money_Receipts",
  EARNING_REPORT: "Earning_Report",
  PROFILE_SETTING: "Profile_Setting",
  STOCK_RESERVATION: "Stock_Reservation",
  STORE_SETTINGS: "Store_Settings",
  AFFILIATED_CUSTOMER_ORDERS: "Affiliated_Customer_Orders",
  DROPSHIPPING: "Dropshipping",

  // school
  INSTITUTE_PROFILE: "Institution_Profile",
  ROLE_PERMISSION: "Role_Permission",
  TEACHER: "Teacher",
  STUDENTS: "Students",
  EMPLOYEE: "Employee",
  ClASSES: "Classes",
  SUBJECTS: "Subjects",
  SECTION: "Section",
  PROFILE: "Profile",
  ROUTINE: "Routine",
  FESS: "Fees",
  TERM: "Term",
  ACCOUNT: "Account",
  DASHBOARD: "Dashboard",
  TRANSACTION: "Transaction",
  TRANSFER_REQUEST: "Transfer_request",
  ADDITIONAL_FEE: "Additional_fees",
  COLLECT_FEE: "Collect_fees",
  TUITION_FEES_PAYMENT: "Tuition_fees_Payment",
  PAYROLL: "Payroll",
  PAYMENT: "Payment",
  NOTICE: "Notice",
  RULES: "Rules",
  SMS: "Sms",
  SHIFT: "Shift",
  EXAM: "Exam",
  LEAVE: "Leave",
  EXAM_Hall: "Exam_Hall",
  GRADE_MARK: "Grade_Mark",
  EXAM_Receipts: "Exam_RECEIPTS",
  EXAM_MARK: "Exam_Mark",
  FAIL_MARK: "Fail_Mark",
  RESULT: "Result",
  RESULT_MIGRATION: "Result_Migration",
  ADMISSION: "Admission",
  DEPARTMENT: "Department",
  ADMISSION_SESSION: "Admission_Session",
  STUDENT_ATTENDANCE: "Student_Attendance",
  TEACHER_ATTENDANCE: "Teacher_Attendance",
  CASH: "Cash",
  CLAIM: "Claim",
  SCHEDULE: "Schedule",
  INVOICE: "Invoice",
  VENDOR: "Vendor",
  HOLIDAY: "Holiday",
  ADMIT: "Admit",
  TICKET: "Ticket",
  VENDOR_ENTRY: "Vendor_Entry",
  INVOICE_ENTRY: "Invoice_Entry",
  ATTENDANCE_REPORT: "attendance_Report",
} as const;

export type TagType = (typeof TagTypes)[keyof typeof TagTypes];
